defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  username: rails_postgres
  password: development

development:
  <<: *defaults
  database: expensable_development

test:
  <<: *defaults
  database: expensable_test
